#pragma once

enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_END};

enum OBJ_LIST { OBJ_PLAYER, OBJ_MONSTER, OBJ_BLOCK, OBJ_ITEM, OBJ_END };

enum ITEM_TYPE { ITEM_COIN, ITEM_MUSHROOM, ITEM_STAR, ITEM_FLOWER, ITEM_END };